In [2]:
import numpy as np

In [20]:
#法一(消去)



def ryDet1(A): 

     

    n= A.shape[0] 

    if n>1: 

        i= 0 

        Bi=  np.delete(A, i, axis=0) 

        #print(f'\ni= {i}, Bi= \n{Bi}') 

         

        det= 0 

        for j in range(n): 

             

            Bij= np.delete(Bi,j, axis=1) 

            print(f'\ni,j= {i}{j}, Bij= \n{Bij}') 

             

            Dij= ryDet1(Bij) #np.linalg.det(Bij) 

            print(f'.... Dij= {Dij}') 

             

            Cij= A[i,j]*Dij*(-1)**(i+j) 

            det += Cij 

        #print(f'det= {det}') 

        return det 

     

    elif A.shape[0]==1: 

        det= A[0,0] 

        return det 

    else: 

        return None 

 


In [21]:
#法二(組合)
def ryDet2(A):
    det2=0
    m=A.shape[0]
    print("det=")
    for n in range(m):
        AA=[[0]*(m-1)for i in range(m-1)]
        for i in range(m-1):
            for j in range(m-1):
                if (j>=n):
                    AA[i][j]=A[i+1][j+1]
                else:
                    AA[i][j]=A[i+1][j]  
        print(f'\n{A[0][n]*((-1)**n)}*{np.array(AA)}') 
        det2+=A[0][n]*((-1)**n)*np.linalg.det(AA) 
    print(f'det= {round(det2)}') 

In [16]:
#生成矩陣
n= 5  

 

np.random.seed(2) 

A= np.random.randint(-5,5,size=(n,n)) 

print(f'A= \n{A}')  

det= np.linalg.det(A) 

print(f'det= {round(det)}') 

A= 
[[ 3  3  1 -3  3]
 [ 2 -3 -4  0 -1]
 [-1  0  2 -2  1]
 [-1 -2  2  1 -4]
 [-2  0  3 -1  1]]
det= -136


In [14]:
ryDet2(A)

det=

3*[[-3 -4  0 -1]
 [ 0  2 -2  1]
 [-2  2  1 -4]
 [ 0  3 -1  1]]

-3*[[ 2 -4  0 -1]
 [-1  2 -2  1]
 [-1  2  1 -4]
 [-2  3 -1  1]]

1*[[ 2 -3  0 -1]
 [-1  0 -2  1]
 [-1 -2  1 -4]
 [-2  0 -1  1]]

3*[[ 2 -3 -4 -1]
 [-1  0  2  1]
 [-1 -2  2 -4]
 [-2  0  3  1]]

3*[[ 2 -3 -4  0]
 [-1  0  2 -2]
 [-1 -2  2  1]
 [-2  0  3 -1]]
det= -136


In [19]:
ryDet1(A)


i,j= 00, Bij= 
[[-3 -4  0 -1]
 [ 0  2 -2  1]
 [-2  2  1 -4]
 [ 0  3 -1  1]]

i,j= 00, Bij= 
[[ 2 -2  1]
 [ 2  1 -4]
 [ 3 -1  1]]

i,j= 00, Bij= 
[[ 1 -4]
 [-1  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[-1]]
.... Dij= -1
.... Dij= -3

i,j= 01, Bij= 
[[ 2 -4]
 [ 3  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= 14

i,j= 02, Bij= 
[[ 2  1]
 [ 3 -1]]

i,j= 00, Bij= 
[[-1]]
.... Dij= -1

i,j= 01, Bij= 
[[3]]
.... Dij= 3
.... Dij= -5
.... Dij= 17

i,j= 01, Bij= 
[[ 0 -2  1]
 [-2  1 -4]
 [ 0 -1  1]]

i,j= 00, Bij= 
[[ 1 -4]
 [-1  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[-1]]
.... Dij= -1
.... Dij= -3

i,j= 01, Bij= 
[[-2 -4]
 [ 0  1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[0]]
.... Dij= 0
.... Dij= -2

i,j= 02, Bij= 
[[-2  1]
 [ 0 -1]]

i,j= 00, Bij= 
[[-1]]
.... Dij= -1

i,j= 01, Bij= 
[[0]]
.... Dij= 0
.... Dij= 2
.... Dij= -2

i,j= 02, Bij= 
[[ 0  2  1]
 [-2  2 -4]
 [ 0  3  1]]

i,j= 00, Bij= 
[[ 2 -4]
 [ 3  1]]


-136