In [10]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[4,11/5,1]])
U = np.array([[1,3,4],[0,-5,-5],[0,0,-3]])
print(L.dot(U))
print(np.dot(L,U))
print(L)
print(U)

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1.  0.  0. ]
 [2.  1.  0. ]
 [4.  2.2 1. ]]
[[ 1  3  4]
 [ 0 -5 -5]
 [ 0  0 -3]]


# A=PLU

In [17]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.18181818 1.        ]]
[[4.         1.         2.        ]
 [0.         2.75       3.5       ]
 [0.         0.         1.36363636]]


In [14]:
print(P@L@U)
print(np.dot(L, U))

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]


# Matrix decompositions

In [149]:
n= 5  

 

np.random.seed(2) 

A= np.random.randint(-5,5,size=(n,n)) 

print(f'A= \n{A}')  

det= np.linalg.det(A) 

print(f'det= {round(det)}') 

A= 
[[ 3  3  1 -3  3]
 [ 2 -3 -4  0 -1]
 [-1  0  2 -2  1]
 [-1 -2  2  1 -4]
 [-2  0  3 -1  1]]
det= -136


In [150]:
#sub-matrix 
det2=0
m=5
for n in range(m):
    AA=[[0]*(m-1)for i in range(m-1)]
    for i in range(m-1):
        for j in range(m-1):
            if (j>=n):
                AA[i][j]=A[i+1][j+1]
            else:
                AA[i][j]=A[i+1][j]  
    print(f'\n{AA}') 
    det2+=A[0][n]*((-1)**n)*np.linalg.det(AA) 
print(f'det= {round(det2)}') 


[[-3, -4, 0, -1], [0, 2, -2, 1], [-2, 2, 1, -4], [0, 3, -1, 1]]

[[2, -4, 0, -1], [-1, 2, -2, 1], [-1, 2, 1, -4], [-2, 3, -1, 1]]

[[2, -3, 0, -1], [-1, 0, -2, 1], [-1, -2, 1, -4], [-2, 0, -1, 1]]

[[2, -3, -4, -1], [-1, 0, 2, 1], [-1, -2, 2, -4], [-2, 0, 3, 1]]

[[2, -3, -4, 0], [-1, 0, 2, -2], [-1, -2, 2, 1], [-2, 0, 3, -1]]
det= -136
