# 3線性方程組

In [2]:
#自己令解，出題目
import numpy as np
# x=5 y=6 z=2
#ex1
x=5 
y=6 
z=2
k1=2*x+5*y+8*z
k2=5*x+2*y+z
k3=8*x+2*y+6*z
k1,k2,k3

(56, 39, 64)

In [3]:
#寫出係數矩陣 A
A = np.array([
    [2, 5, 8],
    [5, 2, 1],
    [8, 2, 6],
    
])
# 寫出常數矩陣 B
B = np.array([56, 39, 64]).reshape(3, 1)
# 找出係數矩陣的反矩陣 A_inv
A_inv = np.linalg.inv(A)
# 將 A_inv 與 B 相乘，即可得到解
ans = A_inv.dot(B)
print(ans)

[[5.]
 [6.]
 [2.]]


In [4]:
B


array([[56],
       [39],
       [64]])

In [7]:
import random
#random.randrange(a, b)  從a到b中隨機產生一筆整數資料
#for number in range(3)

# 5線性方程組

In [8]:
#解
v=[0 for i in range(5)]

for n in range(5):
    v[n]=random.randrange(-5, 5)
    #random.randrange(-5, 5)
v

[-5, -3, 4, 1, 3]

In [9]:
A = [[0]*5 for i in range(5)]
for n in range(5):
    for i in range(5):
        A[n][i]=random.randrange(-5, 5)
A

[[4, 3, -2, -2, 2],
 [-4, -3, -2, 4, -1],
 [4, -3, 2, 2, 0],
 [-1, 4, -1, 2, 2],
 [1, -1, 3, -5, 2]]

In [10]:
#B
Ans = [0 for i in range(5)]
tem=0
for n in range(5):
    for i in range(5):
        Ans[n]+=v[i]*A[n][i]
        #Ans[n]=Ans[n]+tem
        
        
Ans


[-33, 22, -1, -3, 11]

In [11]:
#寫出係數矩陣 AA
AA = np.array(A)

# 寫出常數矩陣 B
B = np.array(Ans).reshape(5, 1)
# 找出係數矩陣的反矩陣 A_inv
AA_inv = np.linalg.inv(AA)
# 將 A_inv 與 B 相乘，即可得到解
ans = AA_inv.dot(B)
print(ans)



[[-5.]
 [-3.]
 [ 4.]
 [ 1.]
 [ 3.]]


# 10線性方程組

In [13]:
#解
v=[0 for i in range(10)]

for n in range(10):
    v[n]=random.randrange(-5, 5)
    #random.randrange(-5, 5)
v

[4, -2, 0, 1, -1, -1, -2, -5, -5, -5]

In [14]:
A = [[0]*10 for i in range(10)]
for n in range(10):
    for i in range(10):
        A[n][i]=random.randrange(-5, 5)
A

[[-5, -3, 2, 3, 0, 0, 4, -4, 4, 0],
 [-3, 3, -1, 3, 2, -2, 2, 1, 2, -3],
 [3, 4, -1, 2, 4, -2, -5, 1, -5, -1],
 [-3, 0, 4, -5, -3, 2, -1, -1, 2, 4],
 [1, -4, -5, 2, -2, -3, 3, 0, -4, 2],
 [-1, -1, -5, 2, 0, 0, 4, 3, 2, 0],
 [0, 3, -3, 3, -4, -3, 1, 3, 2, -4],
 [4, 2, 2, 0, 2, -1, -2, -4, -3, 3],
 [0, -1, -3, 4, 4, 2, -5, -2, -4, -5],
 [-4, -4, -5, -4, 2, -1, -2, 2, -5, 2]]

In [15]:
#B
Ans = [0 for i in range(10)]
for n in range(10):
    for i in range(10):
        Ans[n]+=v[i]*A[n][i]
        #Ans[n]=Ans[n]+tem
        
        
Ans

[-19, -19, 39, -39, 23, -33, -3, 35, 65, -4]

In [16]:
#寫出係數矩陣 AA
AA = np.array(A)

# 寫出常數矩陣 B
B = np.array(Ans).reshape(10, 1)
# 找出係數矩陣的反矩陣 A_inv
AA_inv = np.linalg.inv(AA)
# 將 A_inv 與 B 相乘，即可得到解
ans = AA_inv.dot(B)
print(np.round(ans))  #取整數


[[ 4.]
 [-2.]
 [ 0.]
 [ 1.]
 [-1.]
 [-1.]
 [-2.]
 [-5.]
 [-5.]
 [-5.]]


In [ ]:
#另解
n= np.random.randint(2,10) 

 

np.random.seed(0) 

A= np.random.randint(-5,5,size=(n,n)) 

 

np.random.seed(1) 

b= np.random.randint(-5,5,size=(n,1)) 

 

x= np.linalg.solve(A, b) 
x,A,b